@extends('admin.layouts.app')
@section('title','Experience')
@section('breadcrumb','Experience')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Experience</h1><p class="text-muted mb-0">Manage your professional experience timeline.</p></div><a href="{{ route('admin.experience.create') }}" class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Add Experience</a></div>
<div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Role</th><th>Company</th><th>Period</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
@forelse($experiences as $experience)<tr><td><div class="fw-semibold">{{ $experience->designation }}</div><small class="text-muted">{{ $experience->employment_type }}</small></td><td>{{ $experience->company_name }}<br><small class="text-muted">{{ $experience->location }}</small></td><td>{{ $experience->start_date?->format('M Y') }} — {{ $experience->is_current ? 'Present' : ($experience->end_date?->format('M Y') ?? '—') }}</td><td><span class="badge {{ $experience->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $experience->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end"><a href="{{ route('admin.experience.edit',$experience) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i></a><form method="POST" action="{{ route('admin.experience.destroy',$experience) }}" class="d-inline" onsubmit="return confirm('Delete this experience?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="5" class="text-center py-5 text-muted">No experience records found.</td></tr>@endforelse</tbody></table></div><div class="card-footer">{{ $experiences->links() }}</div></div>
@endsection
