@extends('admin.layouts.app')
@section('title', $blog->exists ? 'Edit Blog Post' : 'New Blog Post')
@section('breadcrumb', $blog->exists ? 'Edit Blog Post' : 'New Blog Post')
@section('content')
<div class="mb-4"><h1 class="h3 mb-1">{{ $blog->exists ? 'Edit Blog Post' : 'New Blog Post' }}</h1><p class="text-muted mb-0">Create useful PHP, Laravel and development content.</p></div>
<form method="POST" action="{{ $blog->exists ? route('admin.blog.update',$blog) : route('admin.blog.store') }}">@csrf @if($blog->exists) @method('PUT') @endif
<div class="row g-4"><div class="col-lg-8"><div class="card shadow-sm"><div class="card-body"><div class="mb-3"><label class="form-label">Title *</label><input name="title" class="form-control form-control-lg" value="{{ old('title',$blog->title) }}" required></div><div class="mb-3"><label class="form-label">Excerpt</label><textarea name="excerpt" class="form-control" rows="3">{{ old('excerpt',$blog->excerpt) }}</textarea></div><div><label class="form-label">Content *</label><textarea name="content" class="form-control" rows="16" required>{{ old('content',$blog->content) }}</textarea></div></div></div></div>
<div class="col-lg-4"><div class="card shadow-sm mb-4"><div class="card-header fw-semibold">Publishing</div><div class="card-body"><div class="mb-3"><label class="form-label">Category</label><select name="blog_category_id" class="form-select"><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('blog_category_id',$blog->blog_category_id)==$category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Author</label><input name="author" class="form-control" value="{{ old('author',$blog->author) }}"></div><div class="mb-3"><label class="form-label">Published At</label><input type="datetime-local" name="published_at" class="form-control" value="{{ old('published_at',$blog->published_at?->format('Y-m-d\TH:i')) }}"></div><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_published" value="1" id="published" @checked(old('is_published',$blog->is_published ?? false))><label class="form-check-label" for="published">Published</label></div></div></div>
<div class="card shadow-sm mb-4"><div class="card-header fw-semibold">SEO & Media</div><div class="card-body"><div class="mb-3"><label class="form-label">Featured Image Path / URL</label><input name="featured_image" class="form-control" value="{{ old('featured_image',$blog->featured_image) }}"></div><div class="mb-3"><label class="form-label">Meta Title</label><input name="meta_title" class="form-control" value="{{ old('meta_title',$blog->meta_title) }}"></div><div class="mb-3"><label class="form-label">Meta Description</label><textarea name="meta_description" class="form-control" rows="3">{{ old('meta_description',$blog->meta_description) }}</textarea></div><div><label class="form-label">Meta Keywords</label><input name="meta_keywords" class="form-control" value="{{ old('meta_keywords',$blog->meta_keywords) }}"></div></div></div>
<button class="btn btn-primary w-100"><i class="bi bi-check2-circle me-2"></i>Save Post</button></div></div></form>
@endsection
